### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by djgragra** [ibBogdan/lovelace-htc-flipclock-weather#6] opened 2021-02-08 17:05 UTC
I am trying the flipclock and it is very nice but unfortunately it is not resposive.
On the computer the full screen is ok but on the tablet the card overlaps the others.
Is it possible to solve this problem?
![full screen](https://user-images.githubusercontent.com/65872226/107255034-2ec04f00-6a38-11eb-9034-453ac3dab9f6.png)
![half screen](https://user-images.githubusercontent.com/65872226/107255041-308a1280-6a38-11eb-9a70-442bb7571357.png)

**Comment by ibBogdan** [comment] 2021-02-12 11:39
i know about this. looking for someone who can help me with it. i`m not a good front end guy :D

**Comment by djgragra** [comment] 2021-02-12 20:32
Ok, I'm editing the code to get a good 769px width display. As soon as I finish it will post the modified code to you.

I had to add classes in the JS file and edited the CSS file

**Comment by ibBogdan** [comment] 2021-05-10 05:37
Duplicate of #11

**Closed by ibBogdan** 2021-05-10 05:37 UTC
