### ISSUE TITLE
Too big on iPhone, and slow rendering

### ISSUE THREAD

**Issue by NiMa08** [ibBogdan/lovelace-htc-flipclock-weather#2] opened 2020-10-08 13:32 UTC
Love this design! But on a iPhone the images are too big and make the other cards shrink, it also takes a long time to render. Is there a solution to this?

Kind regards.

**Comment by clau-bucur** [comment] 2020-10-10 12:18
Love it too, but it's so slow... It takes a few seconds to first appear once the page is loaded.

**Comment by ibBogdan** [comment] 2020-10-16 14:26
I think i fixed the rendering issue. I`m looking for a good front end guy to help me out with the layout.

**Comment by clau-bucur** [comment] 2020-10-16 14:35
Will give it a shot later, and get back.
I'm not good at all with frontend, I can't help there.

**Comment by ibBogdan** [comment] 2020-10-16 14:54
> Will give it a shot later, and get back.
> I'm not good at all with frontend, I can't help there.

me neither .. i`ll find one eventually :))

https://github.com/ibBogdan/lovelace-htc-flipclock-weather/releases/tag/v1.2.1 did a small css fix

**Comment by ibBogdan** [comment] 2021-05-10 05:37
Duplicate of #11

**Closed by ibBogdan** 2021-05-10 05:37 UTC
